version: '3.8'

services:
  gateway-bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot_data.json:/app/bot_data.json
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://api.telegram.org/bot' + __import__('os').environ['BOT_TOKEN'] + '/getMe', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3